### ISSUE TITLE
Issue with compile sketch with Arduino 101 

### ISSUE THREAD

**Issue by naits98** [adafruit/Adafruit-Fingerprint-Sensor-Library#29]
**Error message is:**
### Arduino:1.8.1 (Windows 10), Kort"Arduino/Genuino 101"

enroll:29: error: no matching function for call to 'Adafruit_Fingerprint::Adafruit_Fingerprint(SoftwareSerial*)'

 Adafruit_Fingerprint finger = Adafruit_Fingerprint(&mySerial);

                                                             ^

C:\Users\stfa4\AppData\Local\Temp\arduino_modified_sketch_753123\enroll.ino:29:61: note: candidates are:

In file included from C:\Users\stfa4\AppData\Local\Temp\arduino_modified_sketch_753123\enroll.ino:17:0:

C:\Users\stfa4\Desktop\Arduino\libraries\Adafruit-Fingerprint-Sensor-Library-master/Adafruit_Fingerprint.h:77:3: note: Adafruit_Fingerprint::Adafruit_Fingerprint(HardwareSerial*)

   Adafruit_Fingerprint(HardwareSerial *);

   ^

C:\Users\stfa4\Desktop\Arduino\libraries\Adafruit-Fingerprint-Sensor-Library-master/Adafruit_Fingerprint.h:77:3: note:   no known conversion for argument 1 from 'SoftwareSerial*' to 'HardwareSerial*'

C:\Users\stfa4\Desktop\Arduino\libraries\Adafruit-Fingerprint-Sensor-Library-master/Adafruit_Fingerprint.h:72:7: note: constexpr Adafruit_Fingerprint::Adafruit_Fingerprint(const Adafruit_Fingerprint&)

 class Adafruit_Fingerprint {

       ^

C:\Users\stfa4\Desktop\Arduino\libraries\Adafruit-Fingerprint-Sensor-Library-master/Adafruit_Fingerprint.h:72:7: note:   no known conversion for argument 1 from 'SoftwareSerial*' to 'const Adafruit_Fingerprint&'

C:\Users\stfa4\Desktop\Arduino\libraries\Adafruit-Fingerprint-Sensor-Library-master/Adafruit_Fingerprint.h:72:7: note: constexpr Adafruit_Fingerprint::Adafruit_Fingerprint(Adafruit_Fingerprint&&)

C:\Users\stfa4\Desktop\Arduino\libraries\Adafruit-Fingerprint-Sensor-Library-master/Adafruit_Fingerprint.h:72:7: note:   no known conversion for argument 1 from 'SoftwareSerial*' to 'Adafruit_Fingerprint&&'

C:\Users\stfa4\AppData\Local\Temp\arduino_modified_sketch_753123\enroll.ino: In function 'uint8_t getFingerprintEnroll()':

C:\Users\stfa4\AppData\Local\Temp\arduino_modified_sketch_753123\enroll.ino:217:1: warning: control reaches end of non-void function [-Wreturn-type]

 }

 ^

exit status 1
no matching function for call to 'Adafruit_Fingerprint::Adafruit_Fingerprint(SoftwareSerial*)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ladyada** [comment]
hiya you may want to try the latest version we just committed. it fixes many bugs - then use hardware serial not softserial. it compiled for us :)
