### ISSUE TITLE
Copy whole Template Database from one sensor to another sensor...???

### ISSUE THREAD

**Issue by TehseenHasan** [adafruit/Adafruit-Fingerprint-Sensor-Library#41]
please add a function to copy complete fingerprint database from one sensor to other sensor...

**Comment by one-player** [comment]
This is very necessary. If two or more sensors are used, this function would be very useful

**Comment by ladyada** [comment]
is this a school or work assignment? why are so many people asking for this function?

**Comment by ladyada** [comment]
common requirement for *what* - a product? homework assignment?

**Comment by TehseenHasan** [comment]
a project... or many projects .. like a gate through which members go through in and out, etc

**Comment by ladyada** [comment]
you still need to register all their fingerprints though, so why would you have to move the template?

**Comment by TehseenHasan** [comment]
Register only in one sensor than copy the template to other sensor(s) is best way instead of enrolling same person in different sensors.

**Comment by ladyada** [comment]
what fingerprint sensor did you buy, the url? thx

**Comment by TehseenHasan** [comment]
I use this (R305) Sensor: https://hallroad.org/product/r305-fingerprint-scanner-module-in-pakistan/

and also used this (FPM10A) with your library: https://hallroad.org/product/fingerprint-sensor-fpm10a/

both works very good with this library...

**Comment by ladyada** [comment]
great! please email hallroad and ask them to add this feature support

**Comment by TehseenHasan** [comment]
wow What a great suggestion by the way ...!!!  Why don't you tell me before ...  Than can you tell me what is the use of you library..?

**Comment by ladyada** [comment]
ok thanks! please let us know what they say :)

**Comment by dhalbert** [comment]
I think there's a potential security issue, since you could access or steal a sensor and then download the fingerprint profiles to spoof the same fingerprint elsewhere.

**Comment by cyrux03** [comment]
I have 19 fingerprints sensor, but the task is copy the same database in all sensors

**Comment by cyrux03** [comment]
nothing, I still waiting for your help.

**Comment by cyrux03** [comment]
????, why you delete my comment, I have 19 adafruit sensors, I bought the sensors from a reseller in my country, but they are adafruit, model fpm10a

**Comment by ladyada** [comment]
@cyrux03 please don't bump this thread, it wont get you an answer any sooner - we dont know of how to do this task that people keep asking for :)

**Comment by milindrc** [comment]
Please add a function for storing a extracted template, or copying the database.
