### ISSUE TITLE
Algorithm in fingerprint matching module

### ISSUE THREAD

**Issue by AdithyaRamesh243** [adafruit/Adafruit-Fingerprint-Sensor-Library#44]
Hello. Could someone please guide as to what is the fingerprint matching algorithm used in the fingerprint module. What are the steps that occur when fingerprints are matched? Thank you in advance.

**Comment by ladyada** [comment]
all information is in the datasheet https://learn.adafruit.com/adafruit-optical-fingerprint-sensor/downloads

**Comment by AdithyaRamesh243** [comment]
Thank you. But the datasheet only says that the templates are matched. It does not explain how the confidence score is generated or how minutiae are matched etc. Kindly advice.

**Comment by ladyada** [comment]
no idea!
