### ISSUE TITLE
Copy whole Template Database from one sensor to another sensor...???

### ISSUE THREAD

**Issue by GVS-sever** [adafruit/Adafruit-Fingerprint-Sensor-Library#55]
Excuse me. I want to again raise the issue of implementing the rewriting of fingerprint templates from one scanner to another. I appeal to you because you are leaders in the development of software for these scanners.

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/issues/36
