### ISSUE TITLE
Issues with Using the scanner with Hardware serial

### ISSUE THREAD

**Issue by Ebrahim1604** [adafruit/Adafruit-Fingerprint-Sensor-Library#61]
Hello. I am using the fingerprint sensor with TI's Msp430. Although I have managed to port library, It require to use hardware serial. Is there an example code, like enroll, exclusively for hardware serial? I can't really understand the hardware serial commented part's purpose from existing examples. Probably the code for interfacing with Leo, micro will be great as reference. Thanks.

**Comment by ladyada** [comment]
all code is int he repo
