### ISSUE TITLE
R307 fingerprint download and upload issue

### ISSUE THREAD

**Issue by murugansdc** [adafruit/Adafruit-Fingerprint-Sensor-Library#64]
I can extract the fingerprint
==========
FFFFFFFFFFFFFFFFFF0301471F0000FFFEFFFEFFFEF80EF00EF000E000C000C000C000C00080008000800080008000800000000000000000000000000000005F3921229A24C0C2FA3A1D4B13581349321AC184D82BD6EF01FFFFFFFF0200821D3FDB3951120D1657A5A3D63A18A2513311D3943791250F5995CACF591A22123C94A2ED3F9BE3F33C124A8A49134DEF5216CA4700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000154BEF01FFFFFFFF02008203014B110000FFFEFFFEF0FEF006E002C002C0008000800080008000800080FFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000003F10A1FE59960EBE6697E17E1F9C5EDE2C9E5E7E38A05E7E2926DADE1C36C21E61BB54BE53C1553E3510231F3399C7BF45B6D73C49B9AC1C42269978419F5D8C42A302A8000000002D4CEF01FFFFFFFF0800820000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008AFFFFFFFFFFFFFFFFFF
--
Kindly guide me how to upload the above in another finger print sensor R307

**Comment by pratik6158** [comment]
i got  the same issue can someone
