### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Pratikhyadav** [adafruit/Adafruit-Fingerprint-Sensor-Library#70]
In file included from enroll.ino:17:0:
C:\Users\Documents\Arduino\libraries\Adafruit-Fingerprint-Sensor-Library-1.1.3/Adafruit_Fingerprint.h:22:30: fatal error: SoftwareSerial.h: No such file or directory
compilation terminated.
Error compiling.

I am facing this issue .

**Comment by ladyada** [comment]
contact the place you purchased for tech support. thanks!
