### ISSUE TITLE
Sensor taking wrong prints

### ISSUE THREAD

**Issue by Jawad-Tariq** [adafruit/Adafruit-Fingerprint-Sensor-Library#72]
Hi,
I'm making a biometric system for my house by using the FZ2904 Fingerprint Sensor. I buy it from here "https://www.aliexpress.com/item/4000148007554.html?spm=a2g0s.9042311.0.0.27424c4d9dDX1p".
My problem is: When I install it on my door it is taking prints continuously after some time or in Sunlight without placing any finger on the Sensor. I don't know why the sensor is doing that because it Works OK in a room. Can anyone please help me with this matter? If you need code I can attach it. I'm using Adafruit library for this.

**Comment by ladyada** [comment]
please contact seller
