### ISSUE TITLE
compile instructions

### ISSUE THREAD

**Issue by dschere** [adafruit/Adafruit-Fingerprint-Sensor-Library#8]
Forgive me but I don't see a make file. How do I compile it, what are its dependencies?

**Comment by irealabi** [comment]
It depends on your requirements

**Comment by dschere** [comment]
I am trying to compile it on a raspberry pi 2 running Ubuntu 14.04 using the GPIO (/dev/ttyAMA0)

**Comment by ladyada** [comment]
hiya this library is for Arduino only! it wont work at all on Raspberry pi. closing this issue :)
