### ISSUE TITLE
fingerprint sketch

### ISSUE THREAD

**Issue by el-samiyel** [adafruit/Adafruit-Fingerprint-Sensor-Library#80]
When using the fingerprint sketch, there's no serial output on using getFingerprintID. Also when using getFingerprintIDez unknown error is presented.

Any assistance will be much appreciated.

IDE version 1.8.12

**Comment by ladyada** [comment]
please contact the vendor you purchased the fingerprint sensor for tech support :)

**Comment by el-samiyel** [comment]
Its an adafruit fingerprint sensor?

**Comment by ladyada** [comment]
if you purchased it from adafruit please post to the tech support forums
