### ISSUE TITLE
Examples won't work with MEGA

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit-Fingerprint-Sensor-Library#82]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=168325&p=824485#p824485

For a MEGA - current preprocessor logic in example(s) will setup a software serial instance on unsupported pins. Since conditionals are being used, can't simply "manually" set to HW serial, which is what the guide has you do:
https://learn.adafruit.com/adafruit-optical-fingerprint-sensor/wiring-for-use-with-arduino#soft-and-hard-serial-2976065-15

**Comment by ladyada** [comment]
oof should be using hardware serial - mega has tons of serial ports :)

**Comment by caternuson** [comment]
Got a preference between tweaking the preprocessor logic vs. no logic and just commented out code?

**Comment by ladyada** [comment]
confused... why wouldnt it just work with Serial1? 
https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/blob/master/examples/enroll/enroll.ino#L30

**Comment by caternuson** [comment]
Oh, it would. But for a MEGA, the existing preprocessor logic will land you here:
https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/blob/master/examples/enroll/enroll.ino#L25

So either need to add some more layers to the logic (use `__AVR_ATmega2560__`). Or just remove it and rely on commenting / uncommenting as needed (which is what the guide has you do).

**Comment by ladyada** [comment]
oh oh duh i forgot the mega is an avr. yes can you add a check to !defined() for the mega?

**Comment by caternuson** [comment]
Fixed with #83
