### ISSUE TITLE
Add R503 to TFM

### ISSUE THREAD

**Issue by jshep321** [adafruit/Adafruit-Fingerprint-Sensor-Library#84]
The link from here: [https://www.adafruit.com/product/4651] points to this library.  

Nowhere in the README does it state compatibility--only the older sensor.  Please add / update!

**Comment by ladyada** [comment]
it should work, please try it!

**Comment by jshep321** [comment]
OK, will try it this week.  Please update the readme!

**Comment by kattni** [comment]
README updated to include R503.

**Comment by jshep321** [comment]
Worked as mentioned, btw.  Grow interface must be the same. :)
