### ISSUE TITLE
Change the Security Level - Code Line

### ISSUE THREAD

**Issue by mvcarvalho21** [adafruit/Adafruit-Fingerprint-Sensor-Library#94]
I am trying to change the security level of my fingerprint sensor level 1 to level 3. 

I would like to know if it is possible to change de security level of the fingerprint sensor only with a line code command. I tried the command  "uint16_t security_level = 3", but it is not work. Is it really possible or only with the specific program?

Thank you in advance.

**Comment by ladyada** [comment]
the library does not support setting it, if you add working code plesae submit a PR!

**Comment by mvcarvalho21** [comment]
@ladyada thank you so much. I am going to close the issue.
